"""empty message

Revision ID: 5cae9c9867e2
Revises: 8bf352f1d5d4
Create Date: 2023-01-29 13:43:17.524569

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5cae9c9867e2'
down_revision = '8bf352f1d5d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('work_weeks', schema=None) as batch_op:
        batch_op.alter_column('year_week',
               existing_type=sa.VARCHAR(length=7),
               nullable=False)
        batch_op.drop_column('id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('work_weeks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.INTEGER(), nullable=False))
        batch_op.alter_column('year_week',
               existing_type=sa.VARCHAR(length=7),
               nullable=True)

    # ### end Alembic commands ###
