"""empty message

Revision ID: b42cceefaf65
Revises: 
Create Date: 2023-01-28 23:49:03.338196

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b42cceefaf65'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('work_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product', sa.String(length=30), nullable=False),
    sa.Column('product_name', sa.String(length=30), nullable=False),
    sa.Column('short_name', sa.String(length=10), nullable=False),
    sa.Column('item_number', sa.String(length=30), nullable=False),
    sa.Column('lot_id', sa.String(length=5), nullable=False),
    sa.Column('lot_number', sa.Integer(), nullable=False),
    sa.Column('strip_lot_number', sa.Integer(), nullable=False),
    sa.Column('strip_qty', sa.Integer(), nullable=False),
    sa.Column('standard_rate', sa.Integer(), nullable=False),
    sa.Column('standard_time', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('add_datetime', sa.DateTime(), nullable=False),
    sa.Column('load_datetime', sa.DateTime(), nullable=True),
    sa.Column('line', sa.Integer(), nullable=True),
    sa.Column('start_datetime', sa.DateTime(), nullable=True),
    sa.Column('end_datetime', sa.DateTime(), nullable=True),
    sa.Column('pouched_qty', sa.Integer(), nullable=False),
    sa.Column('remaining_qty', sa.Integer(), nullable=False),
    sa.Column('remaining_time', sa.Integer(), nullable=False),
    sa.Column('log', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lot_number'),
    sa.UniqueConstraint('strip_lot_number')
    )
    op.create_table('work_weeks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year_week', sa.String(length=7), nullable=True),
    sa.Column('prod_days', sa.Integer(), nullable=False),
    sa.Column('workday_start_time', sa.Integer(), nullable=False),
    sa.Column('workday_end_time', sa.Integer(), nullable=False),
    sa.Column('lines', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('year_week')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('work_weeks')
    op.drop_table('work_orders')
    # ### end Alembic commands ###
